DROP TABLE IF EXISTS Colour;
DROP TABLE IF EXISTS Connection;
DROP TABLE IF EXISTS Bridge;
DROP TABLE IF EXISTS Icon;
DROP TABLE IF EXISTS Profile;
DROP TABLE IF EXISTS History;
DROP TABLE IF EXISTS Conversation;